// <auto-generated />
using System;
using IoTServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IoTServer.Migrations
{
    [DbContext(typeof(ApiDataContext))]
    [Migration("20190727194709_Object type fix")]
    partial class Objecttypefix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IoTServer.Data.AirConditionerCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<int>("Fan");

                    b.Property<string>("Mode")
                        .IsRequired();

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RawData")
                        .IsRequired();

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.HasIndex("Model", "Temperature", "Fan", "Mode");

                    b.ToTable("air_conditioner_command");
                });

            modelBuilder.Entity("IoTServer.Data.AirConditionerDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("Description");

                    b.Property<int>("Fan");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Mode")
                        .IsRequired();

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SensorId")
                        .HasMaxLength(10);

                    b.Property<int>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("air_conditioner_device");
                });

            modelBuilder.Entity("IoTServer.Data.AirConditionerRoom", b =>
                {
                    b.Property<int>("Id")
                        .HasMaxLength(10);

                    b.Property<int>("AirConditionerDeviceId")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id", "AirConditionerDeviceId");

                    b.HasIndex("Name");

                    b.ToTable("air_conditioner_room");
                });

            modelBuilder.Entity("IoTServer.Data.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("Description");

                    b.Property<string>("HardwareModel")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("sensor");
                });
#pragma warning restore 612, 618
        }
    }
}
